import { Assignee, Project, Task } from "@/types";

export const ASSIGNEES: Assignee[] = [
  { id: "a1", name: "Lena Brooks", initials: "LB", color: "#6366f1" },
  { id: "a2", name: "Sam Chen", initials: "SC", color: "#10b981" },
  { id: "a3", name: "Jordan Lee", initials: "JL", color: "#f59e0b" },
  { id: "a4", name: "Morgan Davis", initials: "MD", color: "#3b82f6" },
  { id: "a5", name: "Alex Kim", initials: "AK", color: "#8b5cf6" },
];

export const CURRENT_USER = ASSIGNEES[0];

export const PROJECTS: Project[] = [
  { id: "p1", name: "Atlas", identifier: "ATL", color: "#6366f1" },
  { id: "p2", name: "Horizon", identifier: "HRZ", color: "#10b981" },
  { id: "p3", name: "Nucleus", identifier: "NUC", color: "#f59e0b" },
];

export const TASKS: Task[] = [
  {
    id: "t1",
    identifier: "ATL-001",
    title: "Audit and refactor legacy API endpoints",
    description:
      "Review existing REST endpoints for consistency, deprecation, and performance issues. Draft a migration plan for v2 with backward compatibility.",
    status: "backlog",
    priority: "medium",
    assignee: ASSIGNEES[0],
    labels: ["Backend", "Tech Debt"],
    createdAt: "2026-01-05T10:00:00Z",
    projectId: "p1",
  },
  {
    id: "t2",
    identifier: "ATL-002",
    title: "Design token system for new design language",
    description:
      "Create shared tokens for typography, spacing, color, and shadows across web and docs.",
    status: "backlog",
    priority: "low",
    assignee: ASSIGNEES[2],
    labels: ["Design", "Frontend"],
    dueDate: "2026-06-01",
    createdAt: "2026-01-06T11:00:00Z",
    projectId: "p1",
  },
  {
    id: "t3",
    identifier: "ATL-003",
    title: "Implement OAuth2 with PKCE for web client",
    description:
      "Replace session auth with OAuth2 PKCE flow and support GitHub and Google providers.",
    status: "todo",
    priority: "high",
    assignee: ASSIGNEES[1],
    labels: ["Auth", "Backend"],
    dueDate: "2026-05-20",
    createdAt: "2026-01-08T09:00:00Z",
    projectId: "p1",
  },
  {
    id: "t4",
    identifier: "ATL-004",
    title: "Set up end-to-end testing with Playwright",
    description:
      "Add smoke tests for login, billing and issue workflows and run in CI.",
    status: "todo",
    priority: "medium",
    assignee: ASSIGNEES[3],
    labels: ["Testing", "DevOps"],
    dueDate: "2026-05-24",
    createdAt: "2026-01-09T14:00:00Z",
    projectId: "p1",
  },
  {
    id: "t5",
    identifier: "HRZ-001",
    title: "Migrate database schema to PostgreSQL 16",
    description:
      "Execute zero-downtime migration and validate ORM compatibility.",
    status: "in-progress",
    priority: "urgent",
    assignee: ASSIGNEES[1],
    labels: ["Backend", "Infrastructure"],
    dueDate: "2026-05-14",
    createdAt: "2026-01-13T08:00:00Z",
    projectId: "p2",
  },
  {
    id: "t6",
    identifier: "ATL-005",
    title: "Redesign onboarding experience",
    description:
      "Build a multi-step setup flow with progress indicator and sample workspace.",
    status: "in-progress",
    priority: "high",
    assignee: ASSIGNEES[2],
    labels: ["Design", "Feature"],
    dueDate: "2026-05-16",
    createdAt: "2026-01-11T09:00:00Z",
    projectId: "p1",
  },
  {
    id: "t7",
    identifier: "HRZ-002",
    title: "Rate limiting middleware for public APIs",
    description:
      "Implement token bucket rate limiting with configurable per-route limits.",
    status: "in-review",
    priority: "high",
    assignee: ASSIGNEES[3],
    labels: ["Backend", "Security"],
    dueDate: "2026-05-12",
    createdAt: "2026-01-14T14:00:00Z",
    projectId: "p2",
  },
  {
    id: "t8",
    identifier: "ATL-006",
    title: "Add keyboard navigation to command palette",
    description:
      "Support fuzzy search, arrow-key navigation, and accessibility announcements.",
    status: "in-review",
    priority: "medium",
    assignee: ASSIGNEES[0],
    labels: ["Accessibility", "Feature"],
    dueDate: "2026-05-19",
    createdAt: "2026-01-14T10:00:00Z",
    projectId: "p1",
  },
  {
    id: "t9",
    identifier: "ATL-007",
    title: "Integrate Stripe billing webhooks",
    description:
      "Handle subscription lifecycle events and keep billing state synchronized.",
    status: "done",
    priority: "high",
    assignee: ASSIGNEES[1],
    labels: ["Backend", "Billing"],
    dueDate: "2026-05-05",
    createdAt: "2026-01-01T09:00:00Z",
    projectId: "p1",
  },
  {
    id: "t10",
    identifier: "NUC-001",
    title: "Set up observability stack with OpenTelemetry",
    description:
      "Configure traces, metrics, and logs with Grafana dashboards.",
    status: "done",
    priority: "medium",
    assignee: ASSIGNEES[0],
    labels: ["DevOps", "Infrastructure"],
    dueDate: "2026-05-06",
    createdAt: "2026-01-03T10:00:00Z",
    projectId: "p3",
  },
  {
    id: "t11",
    identifier: "NUC-002",
    title: "Prototype AI-generated issue summaries",
    description:
      "Assess output quality and define product guardrails before launch.",
    status: "cancelled",
    priority: "none",
    assignee: ASSIGNEES[0],
    labels: ["AI", "Research"],
    dueDate: "2026-06-18",
    createdAt: "2026-01-07T15:05:00Z",
    projectId: "p3",
  },
  {
    id: "t12",
    identifier: "HRZ-003",
    title: "Deprecate legacy cycle archive endpoint",
    description:
      "Remove deprecated endpoint and update dependent clients.",
    status: "cancelled",
    priority: "low",
    assignee: ASSIGNEES[3],
    labels: ["API"],
    createdAt: "2026-01-08T08:25:00Z",
    projectId: "p2",
  },
];
